import { ArrowUpRight, Phone, ShieldCheck, Check, Wrench, Flame, Zap, Droplets } from 'lucide-react';
import type {Job} from '../lib/jobs';
import {displayJobTitle} from '../lib/jobDisplay.mjs';
const assets='/assets/';
const servicePaths:Record<string,string>={'gas-tank':'/services/gas-tank-water-heaters/','tankless':'/services/tankless-water-heaters/','heat-pump':'/services/heat-pump-water-heaters/'};
const serviceLabels:Record<string,string>={'gas-tank':'Gas tank water heater installation',tankless:'Tankless water heater installation','heat-pump':'Heat pump water heater installation',plumbing:'Plumbing'};
const services=[{icon:Flame,title:'Tank water heaters',text:'A dependable replacement, sized for your home and everyday hot water needs.',url:'/services/gas-tank-water-heaters/'},{icon:Droplets,title:'Tankless water heaters',text:'Explore a space-saving system that heats water as you need it.',url:'/services/tankless-water-heaters/'},{icon:Zap,title:'Heat pump water heaters',text:'Considering electric? Understand the fit, space, and installation with our team.',url:'/services/heat-pump-water-heaters/'},{icon:Wrench,title:'Plumbing, too.',text:'Drain lines, leaks, toilets, repiping, sewer lateral replacement, and safety shut-off valves. One crew to call.',url:'/services/plumbing/'}];
export default function Home({jobs}:{jobs:Job[]}){return <>
<div className="utility"><div className="wrap"><span>CA License #1134458 · Licensed & insured</span><a href="tel:6508442305"><Phone size={15}/> Call (650) 844-2305</a></div></div>
<header><div className="wrap nav"><a href="/" aria-label="Water Heater Boys home"><img className="logo" src={assets+'2026/03/logo.svg'} alt="Water Heater Boys"/></a><nav aria-label="Main navigation"><a href="#services">Services</a><a href="/services/gas-tank-water-heaters/">Our work</a><a href="/about-us/">About us</a><a href="#areas">Service areas</a></nav><a className="header-phone" href="tel:6508442305"><Phone size={16}/>(650) 844-2305</a><a className="button small" href="#estimate">Get an estimate <ArrowUpRight size={18}/></a></div></header>
<main><section className="hero"><div className="wrap hero-grid"><div><div className="hero-positioning"><strong>Full-Service Plumbers</strong><span>Water Heater Specialists</span></div><h1>Hot water.<br/>Handled <em>right.</em></h1><p className="hero-description">From water heater replacements to plumbing repairs and repiping, our local Bay Area crew brings straightforward advice and expert service to homes and commercial properties.</p><div className="actions"><a className="button" href="tel:6508442305"><Phone size={18}/>Call (650) 844-2305</a><a className="text-link" href="#estimate">Request an estimate <ArrowUpRight size={18}/></a></div><p className="availability"><Check size={16}/>Same-day & next-day service is typically available</p></div><div className="hero-visual"><div className="photo-frame"><img className="home-hero-photo" src="/assets/brand/water-heater-boys-hero.jpg" width="852" height="1898" fetchPriority="high" alt="Water Heater Boys branded Bradford White gas water heater installation"/></div><div className="warranty"><ShieldCheck size={31}/><div><strong>1-year workmanship warranty</strong><span>Confidence in the work. Long after we leave.</span></div></div><span className="vertical">WATER HEATER BOYS / BAY AREA, CA</span></div></div></section>
<div className="trust"><div className="wrap"><span><ShieldCheck/>Licensed & insured</span><span><Check/>Upfront quotes</span><span><Wrench/>Installation & replacement</span><span><Phone/>Talk to a real person</span></div></div>
<section className="section wrap" id="services"><div className="section-heading"><div><p className="eyebrow">THE RIGHT HELP, RIGHT HERE</p><h2>What can we take<br/>off your list?</h2></div><p>Replacing an old tank? Planning an upgrade?<br/>Find what makes sense for your home or commercial property.</p></div><div className="services">{services.map((s,i)=><a className="service" href={s.url} key={s.title}><div className="service-top"><s.icon size={31} strokeWidth={1.5}/><span>0{i+1}</span></div><h3>{s.title}</h3><p>{s.text}</p><span className="service-link">Explore service <ArrowUpRight size={19}/></span></a>)}</div></section>
<section className="section wrap reviews" id="reviews" aria-labelledby="reviews-heading"><div className="section-heading"><div><p className="eyebrow">FROM OUR CUSTOMERS</p><h2 id="reviews-heading">Hear it from our neighbors.</h2></div></div><div className="elfsight-app-dc5cca55-9398-4cca-a9bd-b80599826663" data-elfsight-app-lazy=""></div></section>
<section className="work-section" id="work"><div className="wrap"><div className="section-heading"><div><p className="eyebrow">RECENT JOBS. REAL WORK.</p><h2>Good work speaks<br/>for itself.</h2></div><a className="text-link" href="/services/gas-tank-water-heaters/">See more installations <ArrowUpRight size={20}/></a></div><div className="projects" id="recent-jobs">{jobs.map(job=><article key={job._id} className="recent-project"><a href={(servicePaths[job.serviceType]||'/services/gas-tank-water-heaters/')+'#job-'+job._id} aria-label={'View '+displayJobTitle(job)+' in '+job.city}><div className="project-photo">{job.photos?.[0]?.url&&<img loading="lazy" width={600} height={680} src={job.photos[0].url+'?w=900&auto=format&fit=max'} alt={job.photos[0].alt||job.title||('Water heater installation in '+job.city)}/>}<span>{job.legacyId?'FROM OUR PORTFOLIO':'RECENT JOB'} / {job.city.toUpperCase()}</span></div><div className="project-caption"><div><h3>{job.city}</h3><p>{job.zip&&<>{job.zip} · </>}{serviceLabels[job.serviceType]||job.serviceType}</p></div><ArrowUpRight size={24}/></div></a><details className="project-details"><summary>Job details</summary>{job.title&&<p><strong>{displayJobTitle(job)}</strong></p>}{job.description&&<p>{job.description}</p>}{job.problem&&<p><strong>The problem:</strong> {job.problem}</p>}{job.workPerformed&&<p><strong>What we did:</strong> {job.workPerformed}</p>}{job.completionDate&&<p>Completed {job.completionDate}</p>}</details></article>)}</div></div></section>
<section className="section wrap about" id="about"><div><p className="eyebrow">STRAIGHTFORWARD FROM THE START</p><h2>A real person.<br/>A clear plan.<br/><span className="muted">Hot water again.</span></h2><p className="about-intro">We’re a family-run Bay Area business. Our approach is simple: explain your options, respect your home, skip the upsells, and take pride in the work.</p><a className="text-link" href="/about-us/">Meet Water Heater Boys <ArrowUpRight size={19}/></a></div><div>{[{title:'Tell us what’s happening.',copy:'Call or send a service request. A leak, no hot water, or a planned upgrade—start with what you know.'},{title:'Understand your options.',copy:'We assess your setup and explain the recommended work and quote, so you can make an informed decision.'},{title:'Leave the installation to us.',copy:'Our crew handles the work, tests the system, and helps you understand your new water heater.'}].map((s,i)=><div className="step" key={s.title}><span>0{i+1}</span><div><h3>{s.title}</h3><p>{s.copy}</p></div></div>)}</div></section>
<section className="area-section" id="areas"><div className="wrap area-grid"><div><p className="eyebrow">PROUD TO WORK WHERE YOU LIVE</p><h2>Across the Bay.<br/>Around the corner.</h2><p>Serving San Francisco, the Peninsula, the East Bay, and the South Bay—all the way down to San Jose.</p><a className="text-link" href="/service-areas/">Explore our service area <ArrowUpRight size={20}/></a></div><div className="cities">{['San Francisco','The Peninsula','East Bay','South Bay','San Jose','Local Bay Area service'].map(c=><span key={c}>{c}<ArrowUpRight size={16}/></span>)}</div></div></section>
<section className="section wrap estimate" id="estimate"><div><p className="eyebrow">LET’S GET IT SORTED</p><h2>Tell us what<br/>you need.</h2><p className="about-intro">Request an estimate using our service form. Prefer a conversation? Give us a call.</p><a className="big-phone" href="tel:6508442305">(650) 844-2305 <ArrowUpRight size={26}/></a><p className="form-note">Submitting this form sends a service request to Water Heater Boys.</p><div className="estimate-points"><span><Check size={17}/>Clear communication</span><span><Check size={17}/>Upfront pricing</span><span><Check size={17}/>Work backed by a 1-year warranty</span></div></div><div className="jobber-shell"><div className="form-title"><h3>Request service</h3><span>Water Heater Boys</span></div><iframe title="Water Heater Boys service request — Jobber" loading="lazy" src="https://clienthub.getjobber.com/hubs/d4758da6-69c1-4a9c-9551-742eb7fb7b7c/public/requests/1581253/embedded_new?source=embedded_inline"/><p className="form-fallback">Form not loading? <a href="https://www.waterheaterboys.com/request-service">Open our service request page ↗</a></p></div></section></main>
<footer><div className="wrap footer-main"><img className="logo" src={assets+'2026/03/logo.svg'} alt="Water Heater Boys"/><p>Good people. Great work.<br/>Hot water you can count on.</p><a href="tel:6508442305">(650) 844-2305 <ArrowUpRight size={20}/></a></div><div className="wrap footer-bottom"><span>© 2026 Water Heater Boys · CA License #1134458</span><nav aria-label="Legal"><a href="/faqs/">FAQs</a><a href="/privacy-policy/">Privacy policy</a><a href="/disclaimer/">Website disclaimer</a></nav></div></footer></>}
